name: Build project

on:
  workflow_dispatch:
  push:
    branches:
      - 'master'
  pull_request:
    branches:
      - '**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3.5.2
    - name: Setup .NET 8
      uses: actions/setup-dotnet@main
      with:
        dotnet-version: 8.x
    - name: Restore
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Publish
      run: dotnet publish -p:PublishProfile=Properties/PublishProfiles/linux-x64.pubxml
    - name: Upload
      uses: actions/upload-artifact@main
      with:
        name: Binaries (linux-x64)
        path: src/bin/Publish/linux-x64
        if-no-files-found: error