name: Build project

on:
  workflow_dispatch:
  push:
    branches:
      - 'master'
  pull_request:
    branches:
      - '**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@main
    - name: Setup .NET 9
      uses: actions/setup-dotnet@main
      with:
        dotnet-version: 9.x
        dotnet-quality: 'ga'
    - name: Restore
      run: dotnet restore src/GlobalServer/NewDarkGlobalServer.csproj
    - name: Build
      run: dotnet build src/GlobalServer/NewDarkGlobalServer.csproj --no-restore
    - name: Publish
      run: dotnet publish src/GlobalServer/NewDarkGlobalServer.csproj -p:PublishProfile=Properties/PublishProfiles/linux-x64.pubxml
    - name: Upload
      uses: actions/upload-artifact@main
      with:
        name: Binaries (linux-x64)
        path: src/GlobalServer/bin/Publish/linux-x64
        if-no-files-found: error
    - name: docker compose build
      run: docker compose build